# Generated by Django 3.0.4 on 2020-03-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('favColor', models.CharField(max_length=255, verbose_name='Favorite Color')),
                ('catsOrDogs', models.CharField(max_length=255, verbose_name='Cats or Dogs')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
